name: Deploy Documentation (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - List all files
        run: |
          echo "=== Root directory ==="
          ls -la
          echo "=== Docs directory ==="
          find docs/ -type f -name "*.md" | sort
          echo "=== Full tree ==="
          tree docs/ || find docs/ -type d -exec echo "DIR: {}" \; -o -type f -exec echo "FILE: {}" \;

      - name: Debug - Check specific files
        run: |
          echo "=== Checking specific files ==="
          echo "exchange/main.md exists:" && ls -la docs/exchange/main.md || echo "NOT FOUND"
          echo "product/main.md exists:" && ls -la docs/product/main.md || echo "NOT FOUND"
          echo "order/main.md exists:" && ls -la docs/order/main.md || echo "NOT FOUND"
          echo "jenkins/main.md exists:" && ls -la docs/jenkins/main.md || echo "NOT FOUND"
          echo "minikube/main.md exists:" && ls -la docs/minikube/main.md || echo "NOT FOUND"

      - name: Debug - Find mkdocs.yml everywhere
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Root directory contents ==="
          ls -la
          echo "=== Looking for mkdocs.yml everywhere ==="
          find . -name "mkdocs.yml" -type f 2>/dev/null || echo "No mkdocs.yml found anywhere"
          echo "=== Looking for *.yml files ==="
          find . -name "*.yml" -type f 2>/dev/null || echo "No .yml files found"
          echo "=== Looking for *.yaml files ==="
          find . -name "*.yaml" -type f 2>/dev/null || echo "No .yaml files found"
          echo "=== Complete directory tree ==="
          find . -type f | head -20

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test MkDocs config
        run: |
          echo "=== Testing MkDocs config ==="
          mkdocs --version
          python -c "import yaml; print('YAML valid:', yaml.safe_load(open('mkdocs.yml'))['nav'])"

      - name: Build documentation (without --strict first)
        run: |
          echo "=== Building without --strict ==="
          mkdocs build --verbose
        continue-on-error: true

      - name: Build documentation (with --strict)
        run: |
          echo "=== Building with --strict ==="
          mkdocs build --strict --verbose

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: success()

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: success()
        with:
          path: './site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4